spring:
  sql:
    init:
      schema-locations: classpath*:db/h2/schema.sql
      data-locations: classpath*:db/h2/data.sql

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG

exchange:
    url: https://open.er-api.com
    api: /v6/latest

security:
  no-auth-list: /api/v1/exchange/data

jwt:
  expire-minute: 60
  secret-key: doha123
  password: 12345


