CREATE TABLE IF NOT EXISTS EXCHANGE (
    EXCHANGE_ID bigint NOT NULL AUTO_INCREMENT,
    USD varchar(100) NOT NULL,
    KRW varchar(100) NOT NULL,
    TIME_LAST_UPDATE_UTC datetime NOT NULL,
    PRIMARY KEY(EXCHANGE_ID)
);