CREATE TABLE IF NOT EXISTS EXCHANGE_RATE (
    EXCHANGE_ID bigint NOT NULL AUTO_INCREMENT,
    USD varchar(100) NOT NULL,
    KRW varchar(100) NOT NULL,
    TIME_LAST_UPDATE_UTC varchar(100) NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(EXCHANGE_ID)
);

CREATE TABLE IF NOT EXISTS USER_INFO (
    USER_ID bigint NOT NULL AUTO_INCREMENT,
    USER_NAME varchar(100) NOT NULL,
    USER_KEY varchar(100) NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ID)
);